name: Simple C# Calculator Test

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Step 1 - Checkout branch
        uses: actions/checkout@v3

      - name: Step 2 - Run test
        run: dotnet test
